// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy8aMht91LhwbKoT1NR0KsSM54AXGfA3M',
    appId: '1:816037135635:web:66b8d71d1c8bc6bd12c6e6',
    messagingSenderId: '816037135635',
    projectId: 'myprojectbmc1-d54fa',
    authDomain: 'myprojectbmc1-d54fa.firebaseapp.com',
    storageBucket: 'myprojectbmc1-d54fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbCbRapS8a6xbk1zp7kQTBZba96pMIKpE',
    appId: '1:816037135635:android:20db4774ea82d35112c6e6',
    messagingSenderId: '816037135635',
    projectId: 'myprojectbmc1-d54fa',
    storageBucket: 'myprojectbmc1-d54fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGfBJ2taDY_8xetiaUnEIwoJbvmbBViCg',
    appId: '1:816037135635:ios:7d0720ade4ac7e7f12c6e6',
    messagingSenderId: '816037135635',
    projectId: 'myprojectbmc1-d54fa',
    storageBucket: 'myprojectbmc1-d54fa.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGfBJ2taDY_8xetiaUnEIwoJbvmbBViCg',
    appId: '1:816037135635:ios:7d0720ade4ac7e7f12c6e6',
    messagingSenderId: '816037135635',
    projectId: 'myprojectbmc1-d54fa',
    storageBucket: 'myprojectbmc1-d54fa.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy8aMht91LhwbKoT1NR0KsSM54AXGfA3M',
    appId: '1:816037135635:web:a8df53aa00b70d9b12c6e6',
    messagingSenderId: '816037135635',
    projectId: 'myprojectbmc1-d54fa',
    authDomain: 'myprojectbmc1-d54fa.firebaseapp.com',
    storageBucket: 'myprojectbmc1-d54fa.firebasestorage.app',
  );
}
